### ISSUE TITLE
Create neg_item from input dataset

### ISSUE THREAD

**Issue by danni9594** [zyang1580/SML#2]
https://github.com/zyang1580/SML/blob/2e1e3eeafa79dadc39cead5e7e701c23f86eac4e/data/dataset2.py#L172-L201

Hi, thank you for your contribution. I have a question regarding the way you generate neg_item from input dataset. As for what I understand from readme and your code comments, the raw input dataset is of the format (user_id, pos_item_id, neg_item_id_1, neg_item_id_2 ... neg_item_id_n), hence the neg_item_id starts from third column. However, the self.neg_flag defined in the above class starts from 1, which is the second column. Can you help explain your code here? Please feel free to correct me if I'm wrong.

Thank you!

**Comment by zyang1580** [comment]
You are right.  It's a bug that we haven't  found before you pointed out. And We have met with Nan problems, it may be caused by this bug. Thank you!
But IMO, this bug will not influence our results, because the following reasons:
(1) In our SML, in each outer loop, we only update transfer and MF (w_t_hat) one epoch (or two) epoch respectively,  the propability of selecting columns_flag = 1 is very low.      
(2) If the columns_flag=1 has been selected,  it may cause large gradients and then make the model crash.
